name: Test

on: push

jobs:
  lint:
    name: Test code base and create coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: update Python
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - run: sudo apt update
      - run: sudo apt install python3.9-dev

      - name: install poetry
        run: pip install poetry
        
      - name: set up poetry
        run: make install

      - name: Run tests
        env:
          DEBUG: TRUE
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: sqlite:///db.sqlite3
        run: make test
      
      - name: create coverage report for CodeClimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
        with:
          coverageCommand: make coverage
